apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hello-arc
  namespace: prod
spec:
  releaseName: hello-arc-prod
  chart:
    version: '3.*'
    git: https://github.com/JuanGonzalez-Synergy/hello_arc.git
    path: charts/hello-arc
    ref: master
  values:
    image:
      repository: JuanGonzalez-Synergy/hello-arc
      tag: latest
    replicaCount: 1
    env:
      name: MESSAGE
      value: Azure Arc enabled K8s GitOps Demo!
