apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cluster-config
  namespace: cluster-config
spec:
  interval: 5m
  releaseName: hello-arc-prod
  chart:
    spec:
      chart: charts/hello-arc
      version: '3.*'
      sourceRef:
        kind: GitRepository
        name: hello-arc
      interval: 1m
  values:
    image:
      repository: JuanGonzalez-Synergy/hello-arc
      tag: latest
    replicaCount: 1
    env:
      name: MESSAGE
      value: Azure Arc enabled K8s GitOps Demo!
